reduce use of depset.to_list()
aspect-build/bazel-lib pull request #236
Opened 2022-09-09 08:19 UTC by jbedard

I'm not sure how much of a difference this will make. WDYT?

I noticed `copy_to_directory` consuming 3-5s in the angular-cli analysis phase which I think this will improve? Also just reduces some duplicate code 🤷

2022-09-09 08:20 UTC, jbedard commented on lib/private/copy_to_directory.bzl
> +        additional_files_depsets: Additional depsets to copy that are not in the DefaultInfo or DirectoryPathInfo of srcs
Is this a public method? If so do we think this is a reasonable API to add?

2022-09-10 00:13 UTC, gregmagolan commented
I don't remember all of the context on this one. Lets go over it together on Monday

2022-09-10 22:38 UTC, jbedard commented on lib/private/glob_match.bzl
> +    exp_len = len(expr)
Although very small the repeated `len()` calls actually showed up when profiling, may as well drop it 🤷

2022-09-12 19:00 UTC, jbedard commented on lib/private/glob_match.bzl
> +    exp_len = len(expr)
Actually I'm going to revert this for now. `len()` should be O(1) so this might be overkill, and isn't related to the main commit. Can maybe do this later...

2022-09-13 00:26 UTC, gregmagolan commented on lib/private/copy_to_directory.bzl
> +            dst_path = skylib_paths.normalize("%s/%s" % (dst.path, output_path))
Using `%s` seems like it would be slower than `"/".join` since it would have to do string token replacements

2022-09-13 00:27 UTC, gregmagolan approved these changes
🌮

2022-09-13 00:31 UTC, gregmagolan requested changes

2022-09-13 00:31 UTC, gregmagolan commented on lib/private/copy_to_directory.bzl
> +        additional_files_depsets: Additional depsets to copy that are not in the DefaultInfo or DirectoryPathInfo of srcs
It is part of the public API exported via `lib/copy_to_directory.bzl`.

Would be simpler to make the existing `additional_files` mutable and accept either a list or a depset. You can check the type of it in the macro and convert it.

2022-09-13 01:01 UTC, gregmagolan approved these changes
:taco:^2

2022-09-13 01:01 UTC, merged