build: fix ci build caching
aspect-build/bazel-lib pull request #25
Opened 2022-01-17 22:23 UTC by kormide

2022-01-17 22:27 UTC, kormide commented on .github/workflows/release.yml
> +      - name: Mount bazel repo cache
I figure we should never mount the action cache for release builds in case there's stamping.

2022-01-17 23:27 UTC, alexeagle commented on .github/workflows/release.yml
> +      - name: Mount bazel repo cache
from slack - we should mount the action cache and rely on our keys being "stable" so they are part of the action key

2022-01-18 00:10 UTC, alexeagle approved these changes

2022-01-19 04:55 UTC, f0rmiga requested changes

2022-01-19 04:55 UTC, f0rmiga commented on .github/workflows/ci.yaml
> +        run: bazel --bazelrc=.github/workflows/ci.bazelrc --bazelrc=.bazelrc test //...
You need to fix the bazelrc at the same time to remove the environment variable from there. The bazelrc DOES NOT support environment variables. You will need to pass the flags that use the `HOME` env var here.

2022-01-19 22:11 UTC, kormide commented on .github/workflows/ci.yaml
> +        run: bazel --bazelrc=.github/workflows/ci.bazelrc --bazelrc=.bazelrc test //...
Fixed. Going through the other PRs to fix this everywhere.

2022-01-20 01:25 UTC, alexeagle commented on .github/workflows/ci.yaml
> +        run: bazel --bazelrc=.github/workflows/ci.bazelrc --bazelrc=.bazelrc test //...
well, you can put `~` character in bazelrc.

I just tested with `common --disk_cache=~/.thing/bazel` and

```
$ ls $HOME/.thing
bazel
```

Sorry to be a PITA but I think it's a lot nicer if the CI configs can rely on the .bazelrc to keep the flags consistent, otherwise it's very error prone to keep the various commands using the same location. It's easy to add some `bazel query ` command or something when the CI config gets long, and not notice that some flags were supposed to be repeated everywhere.

2022-01-20 01:33 UTC, f0rmiga commented on .github/workflows/ci.yaml
> +        run: bazel --bazelrc=.github/workflows/ci.bazelrc --bazelrc=.bazelrc test //...
You are not being a PITA. I agree that what we did so far is more error prone when adding more Bazel commands.

I have mixed feelings about the expansion of ~ in bazelrc. From a person who is used to do Bash, my head spins that it's able to do such a Bash-y thing and not handle environment variables... on the other hand, if I turn the pragmatic mode on, I like it for the reasons you mentioned that makes it less error prone.

2022-01-20 02:04 UTC, alexeagle commented on .github/workflows/ci.yaml
> +        run: bazel --bazelrc=.github/workflows/ci.bazelrc --bazelrc=.bazelrc test //...
I spent some time searching Bazel docs for a mention of the special handling of ~ but failed 😞

2022-01-20 03:36 UTC, kormide commented on .github/workflows/ci.yaml
> +        run: bazel --bazelrc=.github/workflows/ci.bazelrc --bazelrc=.bazelrc test //...
I agree that it's nicer. I'll do another round on the open prs and on the rules-template.

2022-01-20 04:48 UTC, f0rmiga commented on .github/workflows/ci.yaml
> +        run: bazel --bazelrc=.github/workflows/ci.bazelrc --bazelrc=.bazelrc test //...
@alexeagle do you still think it's better even it being undocumented api? Exercise some Hyrum's law here?

2022-01-20 20:01 UTC, kormide commented
Updated.

2022-01-21 08:05 UTC, f0rmiga commented on .github/workflows/ci.yaml
> +        run: bazel --bazelrc=.github/workflows/ci.bazelrc --bazelrc=.bazelrc test //...
```suggestion
        run: bazel --bazelrc=.github/workflows/ci.bazelrc --bazelrc=.bazelrc test //...

```

2022-01-21 08:06 UTC, f0rmiga approved these changes

2022-01-21 16:48 UTC, alexeagle approved these changes

2022-01-21 16:48 UTC, merged